### ISSUE TITLE
不支持react18嘛

### ISSUE THREAD

**Issue by day-xue** [iamyoki/transition-hook#20] opened 2022-08-24 15:28 UTC
有点可惜呀 今天用react- transition- group 的时候没有动画效果 想试试你的

**Comment by iamyoki** [comment] 2022-08-25 01:12
Thanks for asking. react 18 will be supported in the next major version, stay tuned.

I’ll close this issue due to duplicate of https://github.com/iamyoki/transition-hook/issues/17

**Closed as completed by iamyoki** 2022-08-25 01:12 UTC
